export const styles = {
  page: 'min-h-screen bg-neutral-900 pt-32 pb-20',
  container: 'container mx-auto px-8',
  backLink: 'inline-flex items-center gap-2 text-primary-100 hover:text-primary-50 transition-colors mb-12 text-xs uppercase tracking-[0.2em] font-light',
  backIcon: 'w-4 h-4',
  inner: 'max-w-5xl mx-auto',
  headerBlock: 'mb-12',
  meta: 'flex flex-wrap items-center gap-4 mb-6',
  category: 'text-[10px] uppercase tracking-[0.2em] text-primary-100 font-light',
  year: 'text-[10px] uppercase tracking-[0.15em] text-neutral-400',
  title: 'text-5xl md:text-7xl font-bold text-primary-50 mb-6 tracking-tight leading-[0.95]',
  description: 'text-lg text-primary-100 leading-relaxed font-light max-w-2xl',
  imageWrapper: 'aspect-video bg-neutral-800 mb-16 overflow-hidden',
  image: 'w-full h-full object-cover',
  sectionBlock: 'mb-16',
  sectionTitle: 'text-xs uppercase tracking-[0.3em] text-primary-100 font-light mb-8',
  techList: 'flex flex-wrap gap-4',
  techTag: 'text-xs text-primary-100 font-light tracking-wide border border-neutral-700 px-4 py-2',
  detailText: 'text-base text-primary-100 font-light leading-relaxed max-w-2xl',
  viewProjectLink: 'inline-flex items-center gap-2 mt-8 text-xs uppercase tracking-[0.2em] text-primary-100 hover:text-primary-50 transition-colors font-light border-b border-primary-100 pb-1',
  relatedSection: 'pt-12 border-t border-neutral-700',
  relatedGrid: 'grid grid-cols-1 md:grid-cols-3 gap-6',
  relatedCard: 'group overflow-hidden',
  relatedImageWrapper: 'aspect-video bg-neutral-800 relative overflow-hidden mb-4',
  relatedImage: 'w-full h-full object-cover transition-all duration-500',
  relatedCategory: 'text-[10px] uppercase tracking-[0.2em] text-neutral-400 mb-1',
  relatedTitle: 'text-sm text-primary-50 font-light group-hover:text-primary-100 transition-colors',
} as const;
