export const styles = {
  section: 'py-24 bg-neutral-900',
  container: 'container mx-auto px-8',
  inner: 'max-w-4xl mx-auto',
  sectionBlock: 'mb-16',
  sectionTitle: 'text-xs uppercase tracking-[0.3em] text-primary-100 font-light mb-8',
  groupList: 'space-y-8',
  groupCard: 'border-l border-neutral-700 pl-8 py-2',
  accordionButton: 'w-full text-left',
  accordionHeader: 'flex items-start justify-between gap-4',
  entityTitle: 'text-lg font-semibold text-primary-50 tracking-tight',
  roleTitle: 'text-base text-primary-100 mb-1',
  roleTitleSummary: 'text-base text-primary-100 mt-1',
  date: 'text-xs uppercase tracking-[0.15em] text-neutral-400 mb-4',
  dateSummary: 'text-xs uppercase tracking-[0.15em] text-neutral-400 mt-2',
  chevron: 'w-4 h-4 mt-1 text-primary-100 transition-transform',
  chevronOpen: 'w-4 h-4 mt-1 text-primary-100 transition-transform rotate-180',
  expandedContent: 'mt-6 space-y-10',
  descriptionList: 'space-y-2',
  descriptionItem: 'text-sm text-primary-100 font-light flex gap-3 leading-relaxed',
  dash: 'text-neutral-500 mt-0.5 shrink-0',
  dispatcher: 'text-xs text-neutral-400 mt-2 tracking-wide',
} as const;
